create table Symptom (
    id uuid primary key default uuid_generate_v4(),
    name varchar(100) unique not null,
    status boolean default true not null
);

insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Constipação');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Diarreia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Coceira');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Coceira Anal');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Coceira Genital');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Difuldade em Engolir Alimentos');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Má Digestão/Dispepsia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Dor Aguda');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Dor Crônica');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Gases');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Náusea');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Vômito');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Sensação de Obstrução');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Soluços');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Tosse com Sangue');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Hemorragia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Hematomas');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Sangramento');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Sangue no Sêmen');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Hematúria', true);
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Cãinbras Musculares');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Desmaio');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Dormência');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Insônia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Sonolência');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Amnésia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Tontura');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Vertigem');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Tremor');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Estridor');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Palpitações');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Tosse');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Sibilos');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Choro');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Coriza');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Corrimento');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Perda de Audição');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Secreção no Ouvido');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Ressonar/Ronco');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Zumbido');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Perda do Olfato');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Anisocoria');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Edema');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Inchaço');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Moscas Volantes');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Olhos Lacrimejantes');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Olhos Salientes');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Perda de Visão');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Pontos Flutuantes');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Vermelhidão');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Visão Dupla');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Visão embaçada');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Falta de Ar');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Alterações de Comportamento e/ou Personalidade');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Dor de Cabeça');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Febre');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Fraqueza');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Icterícia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Disfunção Erétil');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Urticária');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Ereção Involuntária');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Incontinência');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Dor ao Urinar');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Retenção');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Urina Incessante');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Amenorreia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Cólicas');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Nódulos');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Secreções');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Caroços');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Massa Cervical');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Boca Seca');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Feridas');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Inflamações');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Mau Hálito');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Alopecia');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Hirsutimo');
insert into Symptom (description, onlyDetectedByMedicalAnalysis) values ('Outro');